### ISSUE TITLE
membros sem dereitos

### ISSUE THREAD

**Issue by ibarraespinosa** [iagdevs/cursoR#12]
A Camila perceveu que os membros não tem dereitos de ADM. 

Me esquecí de mudar isso quando crei o grupo. Agora todos os membros são ADMS.

Abs

**Comment by Isabela192** [comment]
Sérgio, acho que eu não estou como membro do IAGdevs

**Comment by ibarraespinosa** [comment]
ja te convidei novamente. Tu poderia confirmar aceitoun  o convite?

**Comment by cclopes** [comment]
Agora ela é um membro sim 😸
