### ISSUE TITLE
Nomes dos Capítulos e Seções

### ISSUE THREAD

**Issue by cclopes** [iagdevs/cursoR#14]
Fiz algumas atualizações nos títulos e percebi que, ao abrir um capítulo qualquer, **os nomes dos outros capítulos e sessões voltam à versão anterior**. Quando abro o capítulo que supostamente está com problema, **os nomes estão atualizados**.

Alguém tem ideia do porquê?

**Comment by ibarraespinosa** [comment]
Revisa as referencias {#}, da uma olhada no livro https://bookdown.org/yihui/bookdown/

**Comment by Isabela192** [comment]
@cclopes Camila, eu não entendi o que exatamente está acontecendo, qual o capitulo com problema?

**Comment by cclopes** [comment]
Aparentemente está normal agora. Talvez tenha dado algum erro quando eu compilei e o commit de alguém resolveu.
